// Anuncios ganadores mockeados para el método "Espionaje" (Cesar Ortegón).
// Basado en RB-001-dropshippers-creativos-ventas.md: herramientas y métricas reales
// que usan los dropshippers avanzados para evaluar un anuncio antes de replicarlo.

export type SpySourceTool =
  | 'AdSpy'
  | 'Minea'
  | 'Foreplay'
  | 'Kalodata'
  | 'Ecomhunt'
  | 'Dropkiller'
  | 'Scalboost'
  | 'Biblioteca de Anuncios';

export interface SpyWinningAd {
  id: string;
  productName: string;
  category: string; // coincide con los ids de TRENDING_CATEGORIES
  platform: 'Meta' | 'TikTok';
  sourceTool: SpySourceTool;
  daysActive: number;
  ctrPct: number;
  hookRatePct: number;
  cpmCop: number;
  hookText: string;
  offerType: string;
  anguloVenta: string;
  matchedQuery: string;
}

export const SPY_WINNING_ADS: SpyWinningAd[] = [
  {
    id: 'spy-001',
    productName: 'Difusor de Aromaterapia Ultrasónico',
    category: 'salud',
    platform: 'TikTok',
    sourceTool: 'Minea',
    daysActive: 34,
    ctrPct: 3.8,
    hookRatePct: 62,
    cpmCop: 18500,
    hookText: '"Así huele mi casa desde que dejé de comprar velas caras"',
    offerType: 'Combo 2x1 + envío gratis',
    anguloVenta: 'Aspiracional — mejorar el ambiente del hogar sin gastar en velas costosas',
    matchedQuery: 'difusor',
  },
  {
    id: 'spy-002',
    productName: 'Corrector de Postura Magnético',
    category: 'salud',
    platform: 'Meta',
    sourceTool: 'Foreplay',
    daysActive: 52,
    ctrPct: 3.4,
    hookRatePct: 58,
    cpmCop: 16700,
    hookText: '"Llevo 8 horas sentado y ya no me duele la espalda"',
    offerType: 'Combo + garantía 30 días',
    anguloVenta: 'Dolor cotidiano — dolor lumbar de oficina resuelto con uso pasivo todo el día',
    matchedQuery: 'corrector',
  },
  {
    id: 'spy-003',
    productName: 'Masajeador de Cuello Inteligente',
    category: 'salud',
    platform: 'TikTok',
    sourceTool: 'Scalboost',
    daysActive: 38,
    ctrPct: 4.0,
    hookRatePct: 66,
    cpmCop: 15900,
    hookText: '"El masaje de spa que ya no necesito pagar"',
    offerType: 'Combo 2 unidades',
    anguloVenta: 'Sustituto de servicio — reemplaza el gasto recurrente en masajes profesionales',
    matchedQuery: 'masajeador',
  },
  {
    id: 'spy-004',
    productName: 'Tapete de Yoga Antideslizante',
    category: 'fitness',
    platform: 'TikTok',
    sourceTool: 'Ecomhunt',
    daysActive: 29,
    ctrPct: 4.6,
    hookRatePct: 64,
    cpmCop: 14300,
    hookText: '"Mi gimnasio en casa costó menos que un mes de suscripción"',
    offerType: 'Bundle con bandas de resistencia',
    anguloVenta: 'Ahorro/practicidad — gimnasio en casa vs. mensualidad',
    matchedQuery: 'yoga',
  },
  {
    id: 'spy-005',
    productName: 'Set de Bandas de Resistencia',
    category: 'fitness',
    platform: 'Meta',
    sourceTool: 'AdSpy',
    daysActive: 24,
    ctrPct: 3.9,
    hookRatePct: 60,
    cpmCop: 14100,
    hookText: '"Tonifiqué sin salir de mi cuarto en 21 días"',
    offerType: 'Reto de 21 días + guía PDF',
    anguloVenta: 'Reto/desafío — resultado en tiempo definido, sin gimnasio',
    matchedQuery: 'bandas',
  },
  {
    id: 'spy-006',
    productName: 'Lazo para Saltar Digital',
    category: 'fitness',
    platform: 'TikTok',
    sourceTool: 'Kalodata',
    daysActive: 19,
    ctrPct: 3.2,
    hookRatePct: 53,
    cpmCop: 12600,
    hookText: '"Conté calorías quemadas sin salir del apartamento"',
    offerType: 'Oferta relámpago 24h',
    anguloVenta: 'Practicidad — cardio medible sin equipo grande',
    matchedQuery: 'lazo',
  },
  {
    id: 'spy-007',
    productName: 'Collar GPS Antipérdida para Mascotas',
    category: 'mascotas',
    platform: 'Meta',
    sourceTool: 'Dropkiller',
    daysActive: 61,
    ctrPct: 4.2,
    hookRatePct: 71,
    cpmCop: 15200,
    hookText: '"Se me perdió mi perro 3 veces hasta que instalé esto"',
    offerType: 'Oferta relámpago 24h',
    anguloVenta: 'Miedo/dolor — ansiedad de perder a la mascota, resuelta con localización en tiempo real',
    matchedQuery: 'gps',
  },
  {
    id: 'spy-008',
    productName: 'Cepillo Quitapelos Autolimpiante',
    category: 'mascotas',
    platform: 'Meta',
    sourceTool: 'Biblioteca de Anuncios',
    daysActive: 71,
    ctrPct: 3.1,
    hookRatePct: 55,
    cpmCop: 13900,
    hookText: '"Adiós pelo de perro en el sofá, en 30 segundos"',
    offerType: 'Escasez — quedan 20 unidades',
    anguloVenta: 'Frustración doméstica — limpieza constante de pelo de mascota',
    matchedQuery: 'quitapelos',
  },
  {
    id: 'spy-009',
    productName: 'Rodillo de Jade Facial',
    category: 'belleza',
    platform: 'TikTok',
    sourceTool: 'Minea',
    daysActive: 45,
    ctrPct: 5.1,
    hookRatePct: 68,
    cpmCop: 12800,
    hookText: '"Rutina de 2 minutos que reemplazó mi rutina cara de spa"',
    offerType: 'Antes/Después + testimonio',
    anguloVenta: 'Transformación visible — rutina skincare rápida con resultado percibido inmediato',
    matchedQuery: 'rodillo',
  },
  {
    id: 'spy-010',
    productName: 'Organizador de Zapatos Modular',
    category: 'hogar',
    platform: 'Meta',
    sourceTool: 'Foreplay',
    daysActive: 43,
    ctrPct: 2.9,
    hookRatePct: 50,
    cpmCop: 13400,
    hookText: '"Mi clóset pasó de caos a catálogo de Pinterest"',
    offerType: 'Combo 4 piezas',
    anguloVenta: 'Aspiracional/orden — transformación visual del espacio en segundos',
    matchedQuery: 'organizador',
  },
  {
    id: 'spy-011',
    productName: 'Aro de Luz LED con Trípode',
    category: 'tecnologia',
    platform: 'TikTok',
    sourceTool: 'Scalboost',
    daysActive: 22,
    ctrPct: 3.6,
    hookRatePct: 57,
    cpmCop: 13100,
    hookText: '"Así grabo contenido de estudio desde mi cuarto"',
    offerType: 'Combo + envío gratis',
    anguloVenta: 'Aspiracional creador — calidad profesional accesible para contenido propio',
    matchedQuery: 'aro',
  },
  {
    id: 'spy-012',
    productName: 'Billetera Tarjetero de Aluminio',
    category: 'moda',
    platform: 'Meta',
    sourceTool: 'Ecomhunt',
    daysActive: 33,
    ctrPct: 2.7,
    hookRatePct: 48,
    cpmCop: 11800,
    hookText: '"Me clonaron una tarjeta hasta que empecé a usar esto"',
    offerType: 'Combo 2 colores',
    anguloVenta: 'Miedo/seguridad — protección antirrobo de datos (RFID) como diferenciador',
    matchedQuery: 'billetera',
  },
  {
    id: 'spy-013',
    productName: 'Cámara Digital para Niños',
    category: 'ninos',
    platform: 'TikTok',
    sourceTool: 'AdSpy',
    daysActive: 27,
    ctrPct: 4.4,
    hookRatePct: 69,
    cpmCop: 14700,
    hookText: '"El regalo que mi hijo usó todos los días del viaje"',
    offerType: 'Combo + tarjeta de memoria',
    anguloVenta: 'Emocional/regalo — primer dispositivo propio del niño, sin pantallas de adulto',
    matchedQuery: 'cámara',
  },
  {
    id: 'spy-014',
    productName: 'Bocina Flotante Impermeable',
    category: 'hogar',
    platform: 'TikTok',
    sourceTool: 'Kalodata',
    daysActive: 17,
    ctrPct: 4.9,
    hookRatePct: 73,
    cpmCop: 16200,
    hookText: '"Mi piscina ahora suena como un concierto"',
    offerType: 'Escasez — stock global agotándose',
    anguloVenta: 'Aspiracional/entretenimiento — fiestas y piscina sin cables ni cuidado',
    matchedQuery: 'bocina',
  },
  {
    id: 'spy-015',
    productName: 'Guantes Térmicos Calefactables',
    category: 'fitness',
    platform: 'Meta',
    sourceTool: 'Biblioteca de Anuncios',
    daysActive: 12,
    ctrPct: 3.3,
    hookRatePct: 51,
    cpmCop: 12900,
    hookText: '"Ya no se me congelan las manos haciendo ejercicio afuera"',
    offerType: 'Preventa con descuento anticipado',
    anguloVenta: 'Dolor estacional — frío como barrera para mantener rutina de ejercicio',
    matchedQuery: 'guantes',
  },
];
