// Fase 1 — validación local (sin Supabase). Generado a partir del cruce del Excel
// "Encuesta_ Clasificacion_Marcas_17_ Marzo_15_Julio_2026.xlsx" siguiendo
// esquema_medicion_onboarding_brands.md. Corte de datos: 15-jul-2026 (órdenes en T-1 → 14-jul).

export type EstadoMeta7d = "exito" | "fracaso" | "en_observacion" | "sin_signed_up";
export type Gatillo = "gatillo_cerrado" | "activacion_sin_atribucion_cerrada" | "sin_atribucion";
export type Etapa = "entrego" | "activo_sin_entrega" | "no_activo";

export interface ResultadoRow {
  userId: number;
  submittedAt: string;
  signedUp: string;
  primeraOrden: string | null;
  ttfoDias: number | null;
  estadoMeta7d: EstadoMeta7d;
  gatillo: Gatillo;
  caminos: string;
  ordenesCreadas: number | null;
  ordenesEntregadas: number | null;
  etapa: Etapa;
  /** Respuesta a "7.¿Cuántas ventas realiza tu marca al mes?" de la encuesta de clasificación. */
  ventasMesDeclaradas: string | null;
}

export const CORTE_COHORTE = "2026-07-10";
export const FECHA_CORTE_DATA = "2026-07-14"; // T-1 sobre corte de reporte 15-jul
export const META_DIAS = 7;
export const BASELINE_MEDIANA_HISTORICA = 11;
export const BASELINE_PROMEDIO_HISTORICO = 21;

export const RESULTADO_SEMANAL: ResultadoRow[] = [
  { userId: 943834, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 942939, submittedAt: "2026-07-10", signedUp: "2026-07-09", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "51 a 300 al mes" },
  { userId: 943858, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 943869, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 943930, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 943943, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 939146, submittedAt: "2026-07-10", signedUp: "2026-07-03", primeraOrden: null, ttfoDias: null, estadoMeta7d: "fracaso", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "301 a 1.000 al mes" },
  { userId: 944047, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "51 a 300 al mes" },
  { userId: 944064, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 942353, submittedAt: "2026-07-10", signedUp: "2026-07-08", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 944122, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: "2026-07-10", ttfoDias: 0, estadoMeta7d: "exito", gatillo: "gatillo_cerrado", caminos: "bodega,producto,orden_manual", ordenesCreadas: 1, ordenesEntregadas: 0, etapa: "activo_sin_entrega", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 943192, submittedAt: "2026-07-10", signedUp: "2026-07-09", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 944164, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "bodega", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 944197, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "51 a 300 al mes" },
  { userId: 920785, submittedAt: "2026-07-10", signedUp: "2026-06-08", primeraOrden: null, ttfoDias: null, estadoMeta7d: "fracaso", gatillo: "sin_atribucion", caminos: "bodega,orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 944260, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "51 a 300 al mes" },
  { userId: 944266, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "producto,orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 943998, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "producto,orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Más de 1.000 al mes" },
  { userId: 944365, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "producto,orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 944381, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual,integraciones", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 944406, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "producto,integraciones", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 944445, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual,integraciones", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 944485, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "51 a 300 al mes" },
  { userId: 944538, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 944552, submittedAt: "2026-07-10", signedUp: "2026-07-10", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 944585, submittedAt: "2026-07-11", signedUp: "2026-07-11", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 944615, submittedAt: "2026-07-11", signedUp: "2026-07-11", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 944718, submittedAt: "2026-07-11", signedUp: "2026-07-11", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "integraciones", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 944729, submittedAt: "2026-07-11", signedUp: "2026-07-11", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "bodega,producto,orden_manual,integraciones", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 944845, submittedAt: "2026-07-11", signedUp: "2026-07-11", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "301 a 1.000 al mes" },
  { userId: 945049, submittedAt: "2026-07-11", signedUp: "2026-07-11", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "bodega,producto,orden_manual,integraciones", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 945071, submittedAt: "2026-07-11", signedUp: "2026-07-11", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945194, submittedAt: "2026-07-11", signedUp: "2026-07-11", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945207, submittedAt: "2026-07-11", signedUp: "2026-07-11", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945217, submittedAt: "2026-07-11", signedUp: "2026-07-11", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 945257, submittedAt: "2026-07-11", signedUp: "2026-07-11", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945295, submittedAt: "2026-07-12", signedUp: "2026-07-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945366, submittedAt: "2026-07-12", signedUp: "2026-07-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945446, submittedAt: "2026-07-12", signedUp: "2026-07-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945567, submittedAt: "2026-07-12", signedUp: "2026-07-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945624, submittedAt: "2026-07-12", signedUp: "2026-07-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "bodega", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945650, submittedAt: "2026-07-12", signedUp: "2026-07-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 898300, submittedAt: "2026-07-12", signedUp: "2026-05-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "fracaso", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945803, submittedAt: "2026-07-12", signedUp: "2026-07-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945816, submittedAt: "2026-07-12", signedUp: "2026-07-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "producto,orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945819, submittedAt: "2026-07-12", signedUp: "2026-07-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945860, submittedAt: "2026-07-12", signedUp: "2026-07-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "integraciones", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 945915, submittedAt: "2026-07-12", signedUp: "2026-07-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945972, submittedAt: "2026-07-12", signedUp: "2026-07-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 946073, submittedAt: "2026-07-12", signedUp: "2026-07-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 946086, submittedAt: "2026-07-13", signedUp: "2026-07-13", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 946105, submittedAt: "2026-07-13", signedUp: "2026-07-13", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual,integraciones", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 945999, submittedAt: "2026-07-13", signedUp: "2026-07-12", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 946430, submittedAt: "2026-07-13", signedUp: "2026-07-13", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 946451, submittedAt: "2026-07-13", signedUp: "2026-07-13", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "producto", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 946482, submittedAt: "2026-07-13", signedUp: "2026-07-13", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 946579, submittedAt: "2026-07-13", signedUp: "2026-07-13", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "-" },
  { userId: 946699, submittedAt: "2026-07-13", signedUp: "2026-07-13", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 946956, submittedAt: "2026-07-13", signedUp: "2026-07-13", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "integraciones", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 947074, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Más de 1.000 al mes" },
  { userId: 947128, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "bodega,orden_manual,integraciones", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 947158, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 947197, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "producto,orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 947224, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 845881, submittedAt: "2026-07-14", signedUp: "2026-03-28", primeraOrden: null, ttfoDias: null, estadoMeta7d: "fracaso", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 947308, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 947369, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 947373, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "bodega", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 947415, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 947446, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "producto,orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "51 a 300 al mes" },
  { userId: 903234, submittedAt: "2026-07-14", signedUp: "2026-05-18", primeraOrden: "2026-07-14", ttfoDias: 56, estadoMeta7d: "fracaso", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: 6, ordenesEntregadas: 0, etapa: "activo_sin_entrega", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 947525, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 947649, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual,integraciones", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 947671, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "producto,orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 947758, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 947781, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 947894, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "bodega,orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 947980, submittedAt: "2026-07-14", signedUp: "2026-07-14", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 948012, submittedAt: "2026-07-15", signedUp: "2026-07-15", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "producto,orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "51 a 300 al mes" },
  { userId: 863206, submittedAt: "2026-07-15", signedUp: "2026-04-09", primeraOrden: null, ttfoDias: null, estadoMeta7d: "fracaso", gatillo: "sin_atribucion", caminos: "producto,orden_manual,integraciones", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "51 a 300 al mes" },
  { userId: 948045, submittedAt: "2026-07-15", signedUp: "2026-07-15", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "producto,orden_manual", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Menos de 50 al mes" },
  { userId: 948099, submittedAt: "2026-07-15", signedUp: "2026-07-15", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
  { userId: 948064, submittedAt: "2026-07-15", signedUp: "2026-07-15", primeraOrden: null, ttfoDias: null, estadoMeta7d: "en_observacion", gatillo: "sin_atribucion", caminos: "producto,orden_manual,integraciones", ordenesCreadas: null, ordenesEntregadas: null, etapa: "no_activo", ventasMesDeclaradas: "Aún no vendo" },
];
